---
sudo: false

language: python

python: 3.8

services: docker

install:
  - pip3 install ansible==2.7.7
  - pip3 install testinfra molecule docker

before_script:
  - cd ../
  - mv ansible-sbt triviadata.sbt
  - cd triviadata.sbt

script:
  - molecule test
